// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// users.js
export const USER_CREATED = 'USER_CREATED'

// pusher.js
export const UPDATE_PUSHER_SETTINGS = 'UPDATE_PUSHER_SETTINGS'

// simotel.js
export const UPDATE_SIMOTEL_PROFILES = 'UPDATE_SIMOTEL_PROFILES'
export const UPDATE_USERS_PROFILE = 'UPDATE_USERS_PROFILE'
export const UPDATE_PUSHER_LISTEN_SETTINGS = 'UPDATE_PUSHER_LISTEN_SETTINGS'
